[project]
name = "lights-out-yt"
version = "0.1.0"
description = "Solving Lights Out with two approaches: bit-packed algebra and GPU tensors."
requires-python = ">=3.10"
dependencies = [
    "numba>=0.63.1",
    "numpy>=2.2.6",
]
